import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      fontFamily: {
        'display-lg': ['var(--font-hanken)', 'sans-serif'],
        'headline-lg': ['var(--font-hanken)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-hanken)', 'sans-serif'],
        'title-md': ['var(--font-hanken)', 'sans-serif'],
        'body-lg': ['var(--font-hanken)', 'sans-serif'],
        'body-md': ['var(--font-hanken)', 'sans-serif'],
        'label-md': ['var(--font-geist)', 'sans-serif'],
        'label-sm': ['var(--font-geist)', 'sans-serif'],
        display: ['var(--font-hanken)', 'sans-serif'],
        headline: ['var(--font-hanken)', 'sans-serif'],
        body: ['var(--font-hanken)', 'sans-serif'],
        label: ['var(--font-geist)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      colors: {
        'surface': '#faf9f6',
        'surface-dim': '#dbdad7',
        'surface-bright': '#faf9f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'surface-container': '#efeeeb',
        'surface-container-high': '#e9e8e5',
        'surface-container-highest': '#e3e2e0',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#404849',
        'inverse-surface': '#2f312f',
        'inverse-on-surface': '#f2f1ee',
        'outline': '#707979',
        'outline-variant': '#bfc8c9',
        'surface-tint': '#2b676c',
        'm3-primary': '#003a3e',
        'on-primary': '#ffffff',
        'primary-container': '#0f5257',
        'on-primary-container': '#89c4c9',
        'inverse-primary': '#96d0d6',
        'm3-secondary': '#735c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed65b',
        'on-secondary-container': '#745c00',
        'm3-tertiary': '#482e08',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#62441d',
        'on-tertiary-container': '#dcb382',
        'm3-error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#b2edf2',
        'primary-fixed-dim': '#96d0d6',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#084f54',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-fixed': '#ffddb7',
        'tertiary-fixed-dim': '#eabf8d',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#5e411a',
        'surface-variant': '#e3e2e0',
        'clay-brown': '#C19A6B',
        'ochre-gold': '#D4AF37',
        'emerald-green': '#0F5257',
        'sand': '#faf9f6',

        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        success: { DEFAULT: 'hsl(var(--success))', foreground: 'hsl(var(--success-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        tubali: '24px 24px 12px 12px',
      },
      boxShadow: {
        tubali: '0 4px 6px -1px rgba(15, 82, 87, 0.1), 0 2px 4px -1px rgba(15, 82, 87, 0.06)',
      },
      spacing: {
        unit: '4px',
        'container-margin': '20px',
        gutter: '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      backdropBlur: { glass: '16px' },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'dagi-spin': { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        'dagi-pulse': {
          '0%, 100%': { transform: 'scale(0.8)', opacity: '0.8' },
          '50%': { transform: 'scale(1.1)', opacity: '1' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'dagi-spin': 'dagi-spin 8s linear infinite',
        'dagi-pulse': 'dagi-pulse 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
